### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by filmaj** [denosaurs/crux.land#15]
<img width="537" alt="Screenshot 2024-07-29 at 9 50 27 AM" src="https://github.com/user-attachments/assets/981c1cae-ac98-458d-81a5-dd9ba9b1ec82">

Any chance y'all can renew it? Noticed [tests in our CI are failing](https://github.com/slackapi/deno-slack-hub/actions/runs/10145484471/job/28051268753?pr=55) trying to pull some transient dependency crux.land.

**Comment by eliassjogreen** [comment]
Looking into this 👍

**Comment by Shurtu-gal** [comment]
Hello @eliassjogreen we are facing a similar issue where there is some transitive dependency which is not able to be imported.

[Failing Workflow Run](https://github.com/asyncapi/website/actions/runs/11985291760/job/33417017054#step:4:32)

![image](https://github.com/user-attachments/assets/e32abc4e-f7d4-4c7a-a296-a10ca218a684)

**Comment by eliassjogreen** [comment]
This was solved last time by @crowlKats over at denoland I think. I'll ask them

**Comment by arnaubt** [comment]
Any progress on this? @eliassjogreen

**Comment by eliassjogreen** [comment]
Working on it 👍

**Comment by eliassjogreen** [comment]
This is fixed now. Just waiting on the DNS to propagate.

**Comment by Shurtu-gal** [comment]
Thanks @eliassjogreen. Everything is working great.
