### ISSUE TITLE
Can't access to crux.land

### ISSUE THREAD

**Issue by luna3m** [denosaurs/crux.land#16]
Hello friends, I'm trying to access to this URL https://crux.land/api/get/2KNRVU.ts but seems like the page is broken. Tried to access only to crux.land website and have the same error. Is this a known issue? 
![image](https://github.com/user-attachments/assets/20782523-0e2e-4e9a-b1e3-e20ef0f48339)

**Comment by eliassjogreen** [comment]
Sorry. We recently moved to CF as our DNS and registrar which meant some changes to our TLS/SSL which needed to be fixed. Try again now 👍
